package org.damazio.notifier.notification;

/**
 * Interface that defines a method of sending notifications.
 *
 * @author rdamazio
 */
interface NotificationMethod {
  
  /**
   * Callback to be called after a notification is sent, or its sending
   * fails permanently.
   */
  interface NotificationCallback {
    /**
     * Indicates that the given notification's sending is done (either successfully or with a
     * failure).
     *
     * @param failureReason the exception that caused the failure, if there was one
     */
    void notificationDone(Object target, Throwable failureReason);
  }

  /**
   * Sends a notification to the desktop application.
   * This should never be called if {@link #isEnabled} returns false.
   *
   * @param payload the notification contents to send
   * @param target the target to send to (returned from {@link #getTargets})
   * @param callback callback which is called
   * @param isForeground true if the user actively requested sending this notification,
   *        false if it's being generated by an event
   */
  void sendNotification(byte[] payload, Object target, NotificationCallback callback,
      boolean isForeground);

  /**
   * Returns a set of targets that notifications should be sent to.
   * {@link #sendNotification} will be called once (in parallel) for each target returned.
   */
  Iterable<? extends Object> getTargets();

  /**
   * @return the name of this notification method
   */
  String getName();

  /**
   * @return whether this method is enabled and should be called
   */
  boolean isEnabled();
}
