package org.damazio.notifier.backup;

import android.app.backup.BackupAgentHelper;
import android.app.backup.SharedPreferencesBackupHelper;

/**
 * Backup agent helper for the notifier's data.
 *
 * @author rdamazio
 */
public class NotifierBackupAgentHelper extends BackupAgentHelper {
  /**
   * Name of the preferences, as generated by
   * {@link android.preference.PreferenceManager#getDefaultSharedPreferences}.
   */
  private static final String PREFERENCES_NAME = "org.damazio.notifier_preferences";

  @Override
  public void onCreate() {
    super.onCreate();

    addHelper("sharedPrefs", new SharedPreferencesBackupHelper(this, PREFERENCES_NAME));
  }
}
